# Generated by Django 4.2.6 on 2023-10-16 08:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Lang Name', max_length=200, validators=[django.core.validators.MinLengthValidator(1, 'the name longer than 1 char')])),
            ],
        ),
        migrations.CreateModel(
            name='Rattata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Lang Name', max_length=200, validators=[django.core.validators.MinLengthValidator(4, 'the name longer than 4 char')])),
                ('weight', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.lang')),
                ('rattata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.rattata')),
            ],
        ),
        migrations.AddField(
            model_name='rattata',
            name='lang',
            field=models.ManyToManyField(through='home.Rule', to='home.lang'),
        ),
    ]
